const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
const from=source.indexOf('  const sessionTotals ='),to=source.indexOf('  const aggregateAccountPayments =',from);
assert.ok(from>0&&to>from);
const context=vm.createContext({Map,integerMoney:v=>Math.max(0,Math.round(Number(v||0)))});
vm.runInContext(source.slice(from,to)+';globalThis.api={consumptionChangeAllowed,clearPaymentsWithoutConsumption};',context);
const {consumptionChangeAllowed,clearPaymentsWithoutConsumption}=context.api;
const session={id:'a',session_items:[{id:'x',unit_price:10000,quantity:2,status:'served'},{id:'y',unit_price:5000,quantity:1,status:'served'}],session_payments:[{id:'payment-a',amount:10000}]};
assert.equal(consumptionChangeAllowed(session,'x',{status:'cancelled'}),false);
assert.equal(consumptionChangeAllowed(session,'x',{quantity:1}),true,'Puede quedar exactamente lo abonado o más.');
assert.equal(consumptionChangeAllowed(session,'x',{unit_price:2000}),false);
assert.equal(consumptionChangeAllowed(session,'y',{status:'cancelled'}),true);
const last={...session,session_items:[session.session_items[0]]};
assert.equal(consumptionChangeAllowed(last,'x',{status:'cancelled'}),true,'Quitar el último producto permite retirar todo el consumo.');
const empty={...last,session_items:[{...last.session_items[0],status:'cancelled'}]};
assert.equal(clearPaymentsWithoutConsumption(empty).session_payments.length,0);
assert.equal(clearPaymentsWithoutConsumption(session).session_payments.length,1);
assert.equal(empty.session_payments.length,1,'Se conserva la copia anterior para restaurar ante un rechazo del backend.');
console.log('PASS validación de consumos con abonos: precio/cantidad/eliminación, saldo exacto y cuenta vacía sin abonos.');
